from typing import TypedDict

class AgentState(TypedDict):
    query: str                      # The initial technical R&D prompt or problem statement
    keywords: list[str]             # Extracted search terms generated by LLM parsing
    raw_results: list[dict]         # Combined unsorted entries retrieved from vector DB & external APIs
    ranked_results: list[dict]       # Structured, scored outputs generated by your Gemini ranker
    human_feedback: str             # Intercept state storage: e.g., "approve" or "re-rank: prioritize patents"
    final_report: str               # The finalized executive intelligence summary